'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import { StoreProvider } from './utils/Store'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
      <ToastContainer position="bottom-center" limit={1} />
      <body className={inter.className}>{children}
      </body>
    </html>
    </StoreProvider>
  )
}
