
import './globals.css'
import { Inter } from 'next/font/google'
import { StoreProvider } from './utils/Store'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from "./components/Header"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pak Prints',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header  />
          <ToastContainer position="bottom-center" />
          {children}
        </body>
      </html>
    </StoreProvider>
  )
}
